name: SCA Scan

on:
  pull_request:
    paths:
      - '**/*.js'
      - '**/*.json'
      - '**/*.lock'

jobs:
  sca_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci

      - name: SCA Scan
        run: npm audit --json --production > sca_report.json

      - name: Upload SCA Report
        uses: actions/upload-artifact@v2
        with:
          name: sca-report
          path: sca_report.json

